### ISSUE TITLE
Problem launching command

### ISSUE THREAD

**Issue by mibaldi** [tentenponce/KoinGraph#10]
I have a problem launching command, 
`/Users/mikelbalducieldiaz/.nvm/versions/node/v6.9.5/lib/node_modules/koingraph/node_modules/opn/index.js:11
const wslToWindowsPath = async path => {
                               ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mikelbalducieldiaz/.nvm/versions/node/v6.9.5/lib/node_modules/koingraph/index.js:4:13)
    at Module._compile (module.js:570:32)
`
I use a mac book pro with macOS Mojave 10.14.5 
And my version of node is v6.9.5
The installation return this: 
![image](https://user-images.githubusercontent.com/3670131/60381615-c33e8f00-9a57-11e9-93b2-34867408c9f2.png)

**Comment by mibaldi** [comment]
Now using node v12.4.0 (npm v6.9.0) 
which are the requirements?

**Comment by tentenponce** [comment]
Mine is working on v10.16.0 (LTS Version) I'll to recreate the problem, `opn` is deprecated, I'll also update this on the next release.

**Comment by tentenponce** [comment]
I've tried on v12.4.0 with npm v6.9.0, it works without any problem.
![koingraph](https://user-images.githubusercontent.com/5518758/60386458-8c07c680-9ac7-11e9-8c2b-53eead649478.PNG)

Try to reinstall it:

`npm remove -g koingraph`

Then:

`npm install -g koingraph`

**Comment by mibaldi** [comment]
I changed with "nvm use 12.4.0" and it works
